name: chocolatine
on: [push, pull_request] 
branches: -'**' -'!ga-ignore-*'
jobs: 
  env:
    MIRROR_URL: B-**
    EXECUTABLES: []

    runs-on: ubuntu-latest
  job-1:
    name: check_repository_cleanliness
    runs-on: ubuntu-latest
    steps: 
      -uses: actions/checkout@v3 
      -run: | UNWANTED=$(find . -type f -not -path "./git/*" -name "#*" -or -name "*#" -or -name "*~" -or -name "*pain_au_chocolat*" -or -name "*.a" -or -name "*.o" -or -name "*.so" -or -name "*.gcno" -or -name "*.gcda" -or -name "*.gcov" -or -wholename "*tmp/*" -or -name "*/tmp")
      for FILES in $UNWANTED;
      do 
      echo "::error file=${FILES#./}, title=Unwanted file detected::${FILES#./}"
      done
      if [[-n $UNWANTED]]
      then 
      exit 1
      else 
      echo No unwanted files detected
      fi 

    job-2: 
      needs: job-1
      name: check_program_compilation
      runs-on: epitechcontent/epitest-docker
      steps:
        -uses: actions/checkout@v3
        -run: make
        -run: make clean 
        -run:
    
    job-3:
      needs: [job-1, job-2]
      name: run_tests
      steps:
        -uses: actions/checkout@v3

    job-4:
      needs: [job-1, job-2, job-3, job-4]    
      name: push_to_mirror
