name: chocolatine
on: [push, pull_request] 
branches: -'**' -'!ga-ignore-*'
jobs: 
  env:
    MIRROR_URL: B-**
    EXECUTABLES: []

    runs-on: ubuntu-latest
  job-1:
    name: check_repository_cleanliness
    runs-on: epitechcontent/epitest-docker
    steps: 
      -uses: actions/checkout@v3 pixta-dev/repository-mirroring-action
      -run: | UNWANTED=$(find . -type f -not -path "./git/*" "#*" -or "*#" -or "*~" -or "pain_au_chocolat*" -or ".a" -or ".o" -or ".so" -or ".gcno" -or ".gcda" -or ".gcov" -or "tmp/" -or "/tmp")
      for FILES in $UNWANTED;
      do 
      echo "::error file=${FILES#./}, title=Unwanted file detected::${FILES#./}"
      done
      if [[-n $UNWANTED]]
      then 
      exit 1
      else 
      echo No unwanted files detected
      fi 

    job-2: 
      needs: job-1
      name: check_program_compilation
      runs-on: epitechcontent/epitest-docker
      steps:
        -uses: actions/checkout@v3
        -run: make
        -run: make clean 
        -run:
    
    job-3:
      needs: [job-1, job-2]
      name: run_tests
      steps:
        -uses: actions/checkout@v3

    job-4:
      needs: [job-1, job-2, job-3, job-4]    
      name: push_to_mirror
